name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Setup on Latest MySQL
        uses: mirromutth/mysql-action@1.1
        with:
          host port: 3306
          container port: 3306
          mysql version: "latest"
          mysql database: "startcode"
          mysql user: "dev"
          mysql password: "ax2"
          
      - name: Build with Maven
        run: mvn --batch-mode --update-snapshots verify
      - name: Maven deploy
        run: mvn -Dremote.user=${{ secrets.REMOTE_USER }} -Dremote.password=${{ secrets.REMOTE_PW }} tomcat7:deploy
